In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = pd.DataFrame({
    'x0': [1,2,3,4,5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]
})

In [4]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [5]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [6]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [8]:
from pandas import Series, DataFrame
df2 = DataFrame(data.values, columns=['one', 'two', 'three'])

In [9]:
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [10]:
df3 = data.copy()

In [11]:
df3['strings'] =  ['a', 'b', 'c', 'd', 'e']

In [12]:
df3

x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.0       e

In [13]:
df3.values

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [14]:
model_cols = ['x0', 'x1']

In [15]:
data.loc[:, model_cols].values

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [16]:
data['category'] = pd.Categorical(['a','b', 'a', 'a', 'b'], categories=['a', 'b'])

In [17]:
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [18]:
dummies = pd.get_dummies(data.category, prefix='category')

In [19]:
dummies

category_a  category_b
0           1           0
1           0           1
2           1           0
3           1           0
4           0           1

In [20]:
data_with_dummies = data.drop('category', axis=1).join(dummies)

In [21]:
data_with_dummies

x0    x1    y  category_a  category_b
0   1  0.01 -1.5           1           0
1   2 -0.01  0.0           0           1
2   3  0.25  3.6           1           0
3   4 -4.10  1.3           1           0
4   5  0.00 -2.0           0           1

In [22]:
data = DataFrame({'x0': [1,2,3,4,5], 'x1': [0.01, -0.01, 0.25, -4.1, 0.], 'y':[-1.5, 0., 3.6, 1.3, -2]})

In [23]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [24]:
import patsy

In [25]:
y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [26]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [27]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [28]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [29]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [31]:
patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [32]:
coef, resid, _, _ = np.linalg.lstsq(X,y)

/var/folders/tl/3mcdykwx5g145dz_cpc1vdxc0000gn/T/ipykernel_53771/1767972689.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  coef, resid, _, _ = np.linalg.lstsq(X,y)


In [33]:
coef

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [34]:
coef = Series(coef.squeeze(), index=X.design_info.column_names)

In [35]:
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

In [36]:
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)

In [37]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [38]:
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)

In [39]:
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [40]:
y, X = patsy.dmatrices('y ~ I(x0 + x1)', data)

In [41]:
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

In [43]:
data = DataFrame({'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'], 'key2': [0,1,0,1,0,1,0,0], 'v1': [1,2,3,4,5,6,7,8], 'v2': [-1, 0, 2.5, -0.5, 4, -1.2, 0.2, -1.7]})

In [44]:
y, X = patsy.dmatrices('v2 ~ key1', data)

In [45]:
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [46]:
y, X = patsy.dmatrices('v2 ~ key1 + 0', data)

In [47]:
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

In [48]:
y,X = patsy.dmatrices('v2 ~ C(key2)', data)

In [49]:
X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

In [50]:
data['key2'] =data['key2'].map({0: 'zero', 1: 'one'})

In [51]:
data

key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [52]:
y, X = patsy.dmatrices('v2 ~ key1 + key2', data)

In [53]:
X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [54]:
y, X = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data)

In [55]:
X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

In [56]:
import statsmodels.api as sm

In [57]:
import statsmodels.formula.api as smf

In [58]:
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size= size,
    return mean + np.sqrt(variance) * np.random.randn(*size)

In [59]:
np.random.seed(12345)

In [60]:
N =  100

In [61]:
X = np.c_[dnorm(0, 0.4, size=N), dnorm(0, 0.6, size=N), dnorm(0, 0.2, size=N)]

In [62]:
eps = dnorm(0, 0.1, size=N)

In [63]:
beta = [0.1, 0.3, 0.5]

In [64]:
y = np.dot(X,beta) +eps

In [65]:
X[:5]

array([[-0.12946849, -1.21275292,  0.50422488],
       [ 0.30291036, -0.43574176, -0.25417986],
       [-0.32852189, -0.02530153,  0.13835097],
       [-0.35147471, -0.71960511, -0.25821463],
       [ 1.2432688 , -0.37379916, -0.52262905]])

In [66]:
y[:5]

array([ 0.42786349, -0.67348041, -0.09087764, -0.48949442, -0.12894109])

In [67]:
X_model = sm.add_constant(X)

In [68]:
X_model[:5]

array([[ 1.        , -0.12946849, -1.21275292,  0.50422488],
       [ 1.        ,  0.30291036, -0.43574176, -0.25417986],
       [ 1.        , -0.32852189, -0.02530153,  0.13835097],
       [ 1.        , -0.35147471, -0.71960511, -0.25821463],
       [ 1.        ,  1.2432688 , -0.37379916, -0.52262905]])

In [69]:
model = sm.OLS(y, X)

In [70]:
results = model.fit()

In [71]:
results.params

array([0.17826108, 0.22303962, 0.50095093])

In [72]:
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.430
Model:                            OLS   Adj. R-squared (uncentered):              0.413
Method:                 Least Squares   F-statistic:                              24.42
Date:                Mon, 11 Jul 2022   Prob (F-statistic):                    7.44e-12
Time:                        20:55:23   Log-Likelihood:                         -34.305
No. Observations:                 100   AIC:                                      74.61
Df Residuals:                      97   BIC:                                      82.42
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [73]:
data = DataFrame(X, columns=['col0', 'col1', 'col2'])

In [74]:
data['y'] = y

In [76]:
data[:5]

col0      col1      col2         y
0 -0.129468 -1.212753  0.504225  0.427863
1  0.302910 -0.435742 -0.254180 -0.673480
2 -0.328522 -0.025302  0.138351 -0.090878
3 -0.351475 -0.719605 -0.258215 -0.489494
4  1.243269 -0.373799 -0.522629 -0.128941

In [78]:
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()

In [79]:
results.params

Intercept    0.033559
col0         0.176149
col1         0.224826
col2         0.514808
dtype: float64

In [80]:
results.tvalues

Intercept    0.952188
col0         3.319754
col1         4.850730
col2         6.303971
dtype: float64

In [81]:
results.predict(data[:5])

0   -0.002327
1   -0.141904
2    0.041226
3   -0.323070
4   -0.100535
dtype: float64

In [82]:
init_x = 4

In [83]:
import random

In [91]:
values= [init_x, init_x]

In [92]:
N =1000

In [93]:
b0 = 0.8

In [94]:
b1 = -0.4

In [95]:
noise = dnorm(0, 0.1, N)

In [96]:
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

In [97]:
values

[4,
 4,
 2.247499398428837,
 0.33925567686576186,
 -0.6982899195727197,
 -0.6649772769986597,
 -0.02622288463652772,
 0.4528368297311267,
 0.35165101753789774,
 0.3653870604658267,
 0.11452782892434163,
 -0.2182735679300477,
 -0.257332427686747,
 0.637115500240848,
 0.3177576771007221,
 -0.07316073157575237,
 -0.546235710271989,
 -0.26860947762231896,
 -0.2568883084628301,
 -0.2627993852404232,
 0.003284686308583598,
 0.17238298420925535,
 0.17879163181188185,
 0.1777726535067772,
 0.09351829739614173,
 0.04534569617395381,
 -0.41142339938961875,
 -0.031761739515050236,
 0.4145801052077581,
 0.03090708728007946,
 -0.09313503321273792,
 0.3135213521490004,
 0.22404489314408313,
 0.06986568055082881,
 0.16861905558510937,
 0.2959248623367012,
 -0.08281906482426549,
 -0.035087636172165454,
 0.1702410197442458,
 -0.02254263230459652,
 -0.31809522844479,
 0.16650220324197954,
 0.26745965718563014,
 0.26256458984591285,
 -0.1887593783412993,
 -0.1571628963914821,
 -0.4070886438198967,
 -0.36

In [98]:
MAXLAGS = 5

In [101]:
model = sm.tsa.AR(values)

NotImplementedError: AR has been removed from statsmodels and replaced with statsmodels.tsa.ar_model.AutoReg.

In [103]:
sm.tsa?