In [13]:
import pandas as pd

In [14]:
from pandas import Series, DataFrame

In [15]:
obj = pd.Series([4,7,-5,3])

In [16]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [17]:
obj.values

array([ 4,  7, -5,  3])

In [18]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])

In [20]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [21]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [22]:
obj2['a']

-5

In [23]:
obj2['d'] = 6

In [24]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [25]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [26]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [27]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [28]:
'b' in obj2

True

In [29]:
'e' in obj2

False

In [30]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000,  'Utah': 5000}

In [31]:
obj3= Series(sdata)

In [32]:
obj3 

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
states  = {'California', 'Ohio', 'Oregon', 'Texas'}

In [34]:
obj4 = Series(sdata, index=states)

In [35]:
obj4

Texas         71000.0
Ohio          35000.0
California        NaN
Oregon        16000.0
dtype: float64

In [36]:
pd.isnull(obj4)

Texas         False
Ohio          False
California     True
Oregon        False
dtype: bool

In [37]:
pd.notnull(obj4)

Texas          True
Ohio           True
California    False
Oregon         True
dtype: bool

In [38]:
obj4.isnull()

Texas         False
Ohio          False
California     True
Oregon        False
dtype: bool

In [41]:
obj4.notnull()

Texas          True
Ohio           True
California    False
Oregon         True
dtype: bool

In [42]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [43]:
obj4

Texas         71000.0
Ohio          35000.0
California        NaN
Oregon        16000.0
dtype: float64

In [44]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [45]:
obj4.name = 'population'

In [46]:
obj4.index.name= 'state'

In [47]:
obj4

state
Texas         71000.0
Ohio          35000.0
California        NaN
Oregon        16000.0
Name: population, dtype: float64

In [48]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [49]:
obj.index =  ['Bob', 'Steve', 'Jeff', 'Ryan']

In [50]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [51]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000,2001,2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [52]:
frame = DataFrame(data)

In [53]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [54]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [55]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [56]:
frame2 = DataFrame(data, columns = ['year', 'state',  'pop',  'debt'],  index=['one', 'two', 'three','four', 'five', 'six'])

In [57]:
frame2 

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [59]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [60]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [61]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [62]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [63]:
frame2['debt'] = 16.5

In [64]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [65]:
frame2['debt'] = np.arange(6.)

In [66]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [67]:
val = Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

In [68]:
frame2['debt'] =val

In [69]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [70]:
frame2['eastern'] = frame2.state == 'Ohio'

In [71]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [72]:
del frame2['eastern']

In [73]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [74]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [75]:
frame3 =DataFrame(pop)

In [76]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [77]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [78]:
DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [79]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada':  frame3['Nevada'][:2]}

In [80]:
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [81]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [82]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [83]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [84]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [85]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [87]:
index = obj.index

In [88]:
index

Index(['a', 'b', 'c'], dtype='object')

In [89]:
index[1:]

Index(['b', 'c'], dtype='object')

In [90]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [91]:
labels = pd.Index(np.arange(3))

In [92]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [93]:
obj2 = Series([1.5,-.25, 0], index=labels)

In [94]:
obj2

0    1.50
1   -0.25
2    0.00
dtype: float64

In [97]:
obj2.index is labels

True

In [98]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [99]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [100]:
'Ohio' in frame3.columns

True

In [101]:
2003 in frame3.index

False

In [102]:
dup_labels  = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [103]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [104]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [105]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [106]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [107]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [108]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [109]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [110]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [111]:
frame = DataFrame(np.arange(9).reshape((3,3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [112]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [113]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [114]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [115]:
states = ['Texas', 'Utah', 'California']

In [116]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [117]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['b'] not in index"

In [118]:
obj = Series(np.arange(5.), index=['a' ,'b', 'c', 'd', 'e'])

In [119]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [120]:
new_obj = obj.drop('c')

In [121]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [122]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [123]:
data = DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [124]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [129]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [130]:
obj.drop('c', inplace=True)

In [131]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [132]:
obj.drop('c')

KeyError: "['c'] not found in axis"

In [134]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [135]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [136]:
obj['b']

1.0

In [137]:
obj[1]

1.0

In [138]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [139]:
obj[['b','a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [140]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [141]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [142]:
obj['b': 'c']

b    1.0
c    2.0
dtype: float64

In [143]:
obj['b': 'c'] = 5

In [144]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [145]:
data = DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns = ['one', 'two', 'three', 'four'])

In [146]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [147]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [148]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [149]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [150]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [151]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [152]:
data[data < 5] = 0

In [153]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [155]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [156]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [157]:
data.iloc[[1,2], [3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [158]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [159]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [160]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [161]:
ser = Series(np.arange(3.))

In [162]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [163]:
ser[-1]

KeyError: -1

In [164]:
ser2 = Series(np.arange(3.), index=['a', 'b', 'c'])

In [165]:
ser2[-1]

2.0

In [166]:
ser[:1]

0    0.0
dtype: float64

In [167]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [168]:
ser.iloc[:1]

0    0.0
dtype: float64

In [169]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [170]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [171]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [172]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [173]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [177]:
df1 = DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Oregon'])

In [178]:
df1

b    c    d
Ohio    0.0  1.0  2.0
Texas   3.0  4.0  5.0
Oregon  6.0  7.0  8.0

In [179]:
df2 = DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [180]:
dg2

NameError: name 'dg2' is not defined

In [181]:
df12

NameError: name 'df12' is not defined

In [182]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [183]:
df1 + df2

b   c     d   e
Ohio     3.0 NaN   6.0 NaN
Oregon  15.0 NaN  18.0 NaN
Texas    9.0 NaN  12.0 NaN
Utah     NaN NaN   NaN NaN

In [184]:
df1 = DataFrame({'A': [1,2]})

In [185]:
df2 = DataFrame({'B': [3,4]})

In [186]:
df1

A
0  1
1  2

In [187]:
df2

B
0  3
1  4

In [188]:
df1- df2

A   B
0 NaN NaN
1 NaN NaN

In [189]:
df1 = DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))

In [190]:
df2 = DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

In [191]:
df2.loc[1, 'b'] = np.nan

In [192]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [193]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [194]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [195]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [196]:
1/ df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [199]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [200]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [201]:
arr = np.arange(12.).reshape((3,4))

In [202]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [203]:
arr[0]

array([0., 1., 2., 3.])

In [204]:
arr- arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [214]:
frame = DataFrame(np.arange(12).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [215]:
series = frame.iloc[0]

In [216]:
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [217]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [218]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [219]:
series2 = Series(range(3), index=['b', 'e' ,'f'])

In [220]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [221]:
series3 = frame['d']

In [222]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [223]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [224]:
frame.sub(series3, axis='index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [225]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [226]:
frame

b         d         e
Utah    1.278054  1.107878 -0.484656
Ohio   -0.173833  0.879933 -0.864220
Texas  -1.386032  0.499400 -0.695479
Oregon  0.858365  2.159876  0.956638

In [227]:
np.abs(frame)

b         d         e
Utah    1.278054  1.107878  0.484656
Ohio    0.173833  0.879933  0.864220
Texas   1.386032  0.499400  0.695479
Oregon  0.858365  2.159876  0.956638

In [228]:
f = lambda x:x.max() - x.min()

In [229]:
frame.apply(f)

b    2.664086
d    1.660476
e    1.820858
dtype: float64

In [230]:
frame.apply(f, axis='columns')

Utah      1.762710
Ohio      1.744152
Texas     1.885432
Oregon    1.301511
dtype: float64

In [231]:
def f(x): 
    return Series([x.min(), x.max()], index=['min', 'max'])

In [232]:
frame.apply(f)

b         d         e
min -1.386032  0.499400 -0.864220
max  1.278054  2.159876  0.956638

In [233]:
format = lambda x: '%.2f' % x

In [235]:
frame.applymap(format)

b     d      e
Utah     1.28  1.11  -0.48
Ohio    -0.17  0.88  -0.86
Texas   -1.39  0.50  -0.70
Oregon   0.86  2.16   0.96

In [236]:
frame['e'].map(format)

Utah      -0.48
Ohio      -0.86
Texas     -0.70
Oregon     0.96
Name: e, dtype: object

In [238]:
obj = Series(range(4), index=['d', 'a', 'b' ,'c'])

In [239]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [240]:
frame = DataFrame(np.arange(8).reshape((2,4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])

In [241]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [242]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [243]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [244]:
obj = Series([4,7,-3,2])

In [245]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [246]:
obj = Series([4, np.nan , 7, np.nan, -3,2])

In [247]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [248]:
frame = DataFrame({'b' : [4,7,-3,2], 'a': [0,1,0,1]})

In [249]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [252]:
frame.sort_values(by='b')


b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [253]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [254]:
obj = Series([7,-5,7,4,2,0,4])

In [255]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [256]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [257]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [258]:
frame  = DataFrame({'b': [4.3, 7, -3, 2], 'a':[0,1,0,1], 'c': [-2 ,5, 8, -2.5] })

In [259]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [260]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [261]:
obj = Series(range(5), index=['a', 'a', 'b' ,'b' , 'c'])

In [262]:
onj

NameError: name 'onj' is not defined

In [263]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [264]:
obj.index.is_unique

False

In [265]:
obj['a']

a    0
a    1
dtype: int64

In [266]:
obj['c']

4

In [268]:
df = DataFrame(np.random.randn(4,3) , index=['a', 'a' , 'b' , 'b'])

In [269]:
df

0         1         2
a -1.011773  1.001168 -0.045571
a -1.481131  1.269979 -0.512215
b -1.077106 -0.835693  0.081505
b  1.541226  0.779221  0.663386

In [270]:
df.loc['b']

0         1         2
b -1.077106 -0.835693  0.081505
b  1.541226  0.779221  0.663386

In [271]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one','two' ])

In [272]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [273]:
df.sum()


one    9.25
two   -5.80
dtype: float64

In [275]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [276]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [277]:
df.idxmin()

one    d
two    b
dtype: object

In [278]:
df.idxmax()

one    b
two    d
dtype: object

In [279]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [280]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [281]:
obj = Series(['a', 'a', 'b', 'c'] * 4)

In [282]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [283]:
import pandas_datareader as web
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
volume = DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [284]:
returns = price.pct_change()

In [286]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-06-27  0.000000  0.005209 -0.010497 -0.016159
2022-06-28 -0.029790 -0.006583 -0.031749 -0.034736
2022-06-29  0.013024 -0.008107  0.014738 -0.002798
2022-06-30 -0.018028  0.003411 -0.013179 -0.025691
2022-07-01  0.016164 -0.000496  0.010707 -0.002665

In [287]:
returns['MSFT'].corr(returns['IBM'])

0.482412582236253

In [288]:
returns['MSFT'].cov(returns['IBM'])

0.00015239448431946803

In [289]:
returns.MSFT.corr(returns.IBM)

0.482412582236253

In [290]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.437798  0.758351  0.683190
IBM   0.437798  1.000000  0.482413  0.456880
MSFT  0.758351  0.482413  1.000000  0.785998
GOOG  0.683190  0.456880  0.785998  1.000000

In [291]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000408  0.000151  0.000283  0.000253
IBM   0.000151  0.000291  0.000152  0.000143
MSFT  0.000283  0.000152  0.000343  0.000267
GOOG  0.000253  0.000143  0.000267  0.000337

In [292]:
returns.corrwith(returns.IBM)

AAPL    0.437798
IBM     1.000000
MSFT    0.482413
GOOG    0.456880
dtype: float64

In [293]:
returns.corrwith(volume)

AAPL   -0.074949
IBM    -0.100054
MSFT   -0.074479
GOOG   -0.089887
dtype: float64

In [294]:
obj= Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [295]:
uniques = obj.unique()

In [296]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [297]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [300]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [301]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [302]:
mask = obj.isin(['b', 'c'])

In [303]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [304]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [305]:
to_match = Series(['c', 'a', 'b' ,'b', 'c', 'a'])

In [306]:
unique_vals = Series(['c', 'b', 'a'])

In [307]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [308]:
data = DataFrame({'Qu1': [1,3,4,3,4], 'Qu2': [2,3,1,2,3,], 'Qu3': [1,5,2,4,4]})

In [309]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [310]:
result = data.apply(pd.value_counts).fillna(0)

In [311]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0