In [1]:
from pandas import Series, DataFrame

In [2]:
import pandas as  pd

In [5]:
string_data = Series(['aardvark',  'artichoke', np.nan, 'avocado'])

In [4]:
import numpy as np

In [6]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [7]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [8]:
string_data[0] = None

In [9]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [10]:
from numpy import nan as NA

In [11]:
data = Series([1, NA, 3.5, NA, 7])

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]
                 ])

In [15]:
cleaned = data.dropna()

In [16]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4] = NA

In [20]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [28]:
df = DataFrame(np.random.randn(7,3))

In [22]:
df.iloc[:4, 1] = NA

In [24]:
df.iloc[:2, 2] = NA

In [25]:
df

0         1         2
0  1.129640       NaN       NaN
1 -0.974350       NaN       NaN
2 -0.338209       NaN -2.117927
3  0.100163       NaN -0.355200
4  1.191426 -0.628994  2.386834
5 -1.217539 -0.360745  0.615755
6  0.839690 -0.336783 -0.533798

In [26]:
df.dropna()

0         1         2
4  1.191426 -0.628994  2.386834
5 -1.217539 -0.360745  0.615755
6  0.839690 -0.336783 -0.533798

In [27]:
df.dropna(thresh=2)

0         1         2
2 -0.338209       NaN -2.117927
3  0.100163       NaN -0.355200
4  1.191426 -0.628994  2.386834
5 -1.217539 -0.360745  0.615755
6  0.839690 -0.336783 -0.533798

In [29]:
df

0         1         2
0 -0.620172 -0.894068  0.542642
1 -0.114445 -0.065851  0.120339
2  0.832328 -0.348050 -0.159041
3  0.308598  0.977865 -0.333138
4  0.587189  0.204626 -0.276375
5  1.378071  0.280681 -0.541858
6 -0.257746 -2.093095  0.783979

In [31]:
df.iloc[1,1] = NA

In [32]:
df

0         1         2
0 -0.620172 -0.894068  0.542642
1 -0.114445       NaN  0.120339
2  0.832328 -0.348050 -0.159041
3  0.308598  0.977865 -0.333138
4  0.587189  0.204626 -0.276375
5  1.378071  0.280681 -0.541858
6 -0.257746 -2.093095  0.783979

In [33]:
df.iloc[4,1] = NA

In [34]:
df

0         1         2
0 -0.620172 -0.894068  0.542642
1 -0.114445       NaN  0.120339
2  0.832328 -0.348050 -0.159041
3  0.308598  0.977865 -0.333138
4  0.587189       NaN -0.276375
5  1.378071  0.280681 -0.541858
6 -0.257746 -2.093095  0.783979

In [36]:
df.dropna(thresh=1)

0         1         2
0 -0.620172 -0.894068  0.542642
1 -0.114445       NaN  0.120339
2  0.832328 -0.348050 -0.159041
3  0.308598  0.977865 -0.333138
4  0.587189       NaN -0.276375
5  1.378071  0.280681 -0.541858
6 -0.257746 -2.093095  0.783979

In [37]:
df.iloc[1,2] = NA

In [38]:
df

0         1         2
0 -0.620172 -0.894068  0.542642
1 -0.114445       NaN       NaN
2  0.832328 -0.348050 -0.159041
3  0.308598  0.977865 -0.333138
4  0.587189       NaN -0.276375
5  1.378071  0.280681 -0.541858
6 -0.257746 -2.093095  0.783979

In [39]:
df.dropna(thresh=2)

0         1         2
0 -0.620172 -0.894068  0.542642
2  0.832328 -0.348050 -0.159041
3  0.308598  0.977865 -0.333138
4  0.587189       NaN -0.276375
5  1.378071  0.280681 -0.541858
6 -0.257746 -2.093095  0.783979

In [40]:
df.fillna(0)

0         1         2
0 -0.620172 -0.894068  0.542642
1 -0.114445  0.000000  0.000000
2  0.832328 -0.348050 -0.159041
3  0.308598  0.977865 -0.333138
4  0.587189  0.000000 -0.276375
5  1.378071  0.280681 -0.541858
6 -0.257746 -2.093095  0.783979

In [41]:
df.fillna({1:0.5, 2:0})

0         1         2
0 -0.620172 -0.894068  0.542642
1 -0.114445  0.500000  0.000000
2  0.832328 -0.348050 -0.159041
3  0.308598  0.977865 -0.333138
4  0.587189  0.500000 -0.276375
5  1.378071  0.280681 -0.541858
6 -0.257746 -2.093095  0.783979

In [42]:
_ = df.fillna(0, inplace=True)

In [43]:
df

0         1         2
0 -0.620172 -0.894068  0.542642
1 -0.114445  0.000000  0.000000
2  0.832328 -0.348050 -0.159041
3  0.308598  0.977865 -0.333138
4  0.587189  0.000000 -0.276375
5  1.378071  0.280681 -0.541858
6 -0.257746 -2.093095  0.783979

In [44]:
df = DataFrame(np.random.randn(6,3))

In [45]:
df.iloc[2:,1] = NA

In [46]:
df.iloc[4:,2] = NA

In [47]:
df

0         1         2
0 -0.345106  0.954203  0.291095
1  0.467196  0.237734 -0.428085
2  0.079928       NaN -0.565634
3  0.494969       NaN  0.641106
4 -0.620096       NaN       NaN
5 -1.948132       NaN       NaN

In [49]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -0.345106  0.954203  0.291095
1  0.467196  0.237734 -0.428085
2  0.079928  0.237734 -0.565634
3  0.494969  0.237734  0.641106
4 -0.620096       NaN  0.641106
5 -1.948132       NaN  0.641106

In [50]:
data = Series([1., NA, 3.5, NA, 7])

In [53]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [56]:
data = DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1,1,2,3,3,4,4]})

In [57]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [58]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [59]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [60]:
data['v1'] = range(7)

In [62]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [63]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [64]:
data = DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham',  'nova lox'], 'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [65]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [71]:
meat_to_animal = {'bacon': 'pig', 'pulled pork': 'pig', 'pastrami': 'cow', 'corned beef': 'cow', 'honey ham': 'pig', 'nova lox': 'salmon'}

In [67]:
lowercased = data['food'].str.lower()

In [68]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [72]:
data['animal'] = lowercased.map(meat_to_animal)

In [73]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [74]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [75]:
data = Series([1., -999., 2., -999, -1000, 3])

In [76]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [77]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [78]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [79]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [80]:
data.replace({-999: np.nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [81]:
data = DataFrame(np.arange(12).reshape((3,4)), 
                index= ['Ohio', 'Colorado', 'New York'], columns=['one', 'two', 'three', 'four'])

In [85]:
transform = lambda x: x[:4].upper()

In [86]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [87]:
data.index = data.index.map(transform)

In [88]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [90]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [91]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [92]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [93]:
ata

NameError: name 'ata' is not defined

In [94]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [95]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [96]:
bins = [18,25,35,60,100]

In [97]:
cats = pd.cut(ages, bins)

In [98]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [99]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [100]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [101]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [102]:
pd.cut(ages, [18,26,36,61,100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [103]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged','Senior']

In [104]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [105]:
data = np.random.randn(20)

In [106]:
pd.cut(data, 4, precision=2)

[(-0.93, -0.097], (-0.93, -0.097], (0.74, 1.57], (-0.097, 0.74], (-1.77, -0.93], ..., (0.74, 1.57], (-0.93, -0.097], (-0.93, -0.097], (-0.93, -0.097], (-0.93, -0.097]]
Length: 20
Categories (4, interval[float64, right]): [(-1.77, -0.93] < (-0.93, -0.097] < (-0.097, 0.74] < (0.74, 1.57]]

In [107]:
data = np.random.randn(1000)

In [108]:
cats = pd.qcut(data, 4)

In [109]:
cats

[(-2.6599999999999997, -0.65], (-0.65, 0.00785], (0.00785, 0.735], (-0.65, 0.00785], (0.735, 3.019], ..., (-2.6599999999999997, -0.65], (0.00785, 0.735], (0.735, 3.019], (-2.6599999999999997, -0.65], (-2.6599999999999997, -0.65]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.6599999999999997, -0.65] < (-0.65, 0.00785] < (0.00785, 0.735] < (0.735, 3.019]]

In [110]:
pd.value_counts(cats)

(-2.6599999999999997, -0.65]    250
(-0.65, 0.00785]                250
(0.00785, 0.735]                250
(0.735, 3.019]                  250
dtype: int64

In [111]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1])

[(-2.6599999999999997, -1.233], (-1.233, 0.00785], (0.00785, 1.372], (-1.233, 0.00785], (0.00785, 1.372], ..., (-1.233, 0.00785], (0.00785, 1.372], (1.372, 3.019], (-1.233, 0.00785], (-1.233, 0.00785]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.6599999999999997, -1.233] < (-1.233, 0.00785] < (0.00785, 1.372] < (1.372, 3.019]]

In [112]:
data = DataFrame(np.random.randn(1000, 4))

In [113]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.002820    -0.020581    -0.027294    -0.029693
std       0.985678     0.956016     1.008825     1.022633
min      -2.642013    -3.476877    -3.376443    -3.752352
25%      -0.712260    -0.698255    -0.689239    -0.709316
50%      -0.006588    -0.006877    -0.030945    -0.041080
75%       0.662461     0.642904     0.628895     0.689826
max       3.403428     3.090922     4.069705     3.323493

In [114]:
col = data[2]

In [115]:
col

0     -1.301062
1      0.824500
2     -1.429176
3      1.273328
4      1.208182
         ...   
995   -0.195328
996   -0.312818
997    0.811253
998   -0.092021
999    0.308361
Name: 2, Length: 1000, dtype: float64

In [116]:
col[np.abs(col) > 3]

73    -3.376443
233    3.280434
767    4.069705
Name: 2, dtype: float64

In [117]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
40  -0.236573 -3.341640  1.322918 -0.720342
73   0.773799 -0.297975 -3.376443  1.465973
78   3.023885  0.254754  0.760656 -0.980838
233 -1.220564  0.548166  3.280434 -0.496852
242  0.856745 -3.476877 -0.922609 -0.648723
359 -0.133752 -0.557603 -0.172171 -3.752352
655 -1.757068 -1.302284 -1.076896 -3.156146
712 -0.485712  0.606095  0.218053 -3.090693
767 -0.783011 -1.897206  4.069705  0.834932
828  3.403428  1.487100 -1.613158  1.527981
936 -0.984996  3.090922 -1.026458 -1.125373
986 -0.435987  1.054364  1.740870  3.323493

In [118]:
data[(np.abs(data) > 3).all()]

/var/folders/tl/3mcdykwx5g145dz_cpc1vdxc0000gn/T/ipykernel_28038/3858146807.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[(np.abs(data) > 3).all()]


IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [122]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
40  -0.236573 -3.341640  1.322918 -0.720342
73   0.773799 -0.297975 -3.376443  1.465973
78   3.023885  0.254754  0.760656 -0.980838
233 -1.220564  0.548166  3.280434 -0.496852
242  0.856745 -3.476877 -0.922609 -0.648723
359 -0.133752 -0.557603 -0.172171 -3.752352
655 -1.757068 -1.302284 -1.076896 -3.156146
712 -0.485712  0.606095  0.218053 -3.090693
767 -0.783011 -1.897206  4.069705  0.834932
828  3.403428  1.487100 -1.613158  1.527981
936 -0.984996  3.090922 -1.026458 -1.125373
986 -0.435987  1.054364  1.740870  3.323493

In [124]:
data[(np.abs(data) >3).all()]

/var/folders/tl/3mcdykwx5g145dz_cpc1vdxc0000gn/T/ipykernel_28038/2476082714.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[(np.abs(data) >3).all()]


IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [125]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [127]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.002393    -0.019853    -0.028268    -0.029017
std       0.984294     0.952986     1.002965     1.018415
min      -2.642013    -3.000000    -3.000000    -3.000000
25%      -0.712260    -0.698255    -0.689239    -0.709316
50%      -0.006588    -0.006877    -0.030945    -0.041080
75%       0.662461     0.642904     0.628895     0.689826
max       3.000000     3.000000     3.000000     3.000000

In [128]:
np.sign(data)

0    1    2    3
0    1.0  1.0 -1.0 -1.0
1    1.0 -1.0  1.0 -1.0
2    1.0  1.0 -1.0  1.0
3    1.0 -1.0  1.0 -1.0
4    1.0 -1.0  1.0  1.0
..   ...  ...  ...  ...
995 -1.0  1.0 -1.0 -1.0
996  1.0  1.0 -1.0  1.0
997  1.0  1.0  1.0 -1.0
998  1.0 -1.0 -1.0  1.0
999  1.0 -1.0  1.0 -1.0

[1000 rows x 4 columns]

In [129]:
df = DataFrame(np.arange(5 * 4).reshape((5,4)))

In [130]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [131]:
sampler = np.random.permutation(5)

In [132]:
sampler

array([1, 3, 0, 4, 2])

In [133]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3
4  16  17  18  19
2   8   9  10  11

In [134]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19

In [135]:
df.sample(4)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3

In [136]:
choices = Series([5,7,-1,6,4])

In [137]:
draws = choices.sample(n=10, replace=True)

In [138]:
draws

0    5
1    7
1    7
4    4
2   -1
4    4
2   -1
1    7
3    6
4    4
dtype: int64

In [139]:
df  = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1':range(6)})

In [140]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [141]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [142]:
df_with_dummy = df[['data1']].join(dummies)

In [143]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [144]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [145]:
mnames = ['movie_id', 'title', 'genres']

In [155]:
movies = pd.read_table('datasets/movielens/movies.dat', sep='::', names=mnames)

/var/folders/tl/3mcdykwx5g145dz_cpc1vdxc0000gn/T/ipykernel_28038/2875883383.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table('datasets/movielens/movies.dat', sep='::', names=mnames)


In [156]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [157]:
all_genres = []


In [158]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [159]:
all_genres

['Animation',
 "Children's",
 'Comedy',
 'Adventure',
 "Children's",
 'Fantasy',
 'Comedy',
 'Romance',
 'Comedy',
 'Drama',
 'Comedy',
 'Action',
 'Crime',
 'Thriller',
 'Comedy',
 'Romance',
 'Adventure',
 "Children's",
 'Action',
 'Action',
 'Adventure',
 'Thriller',
 'Comedy',
 'Drama',
 'Romance',
 'Comedy',
 'Horror',
 'Animation',
 "Children's",
 'Drama',
 'Action',
 'Adventure',
 'Romance',
 'Drama',
 'Thriller',
 'Drama',
 'Romance',
 'Thriller',
 'Comedy',
 'Action',
 'Action',
 'Comedy',
 'Drama',
 'Crime',
 'Drama',
 'Thriller',
 'Thriller',
 'Drama',
 'Sci-Fi',
 'Drama',
 'Romance',
 'Drama',
 'Drama',
 'Romance',
 'Adventure',
 'Sci-Fi',
 'Drama',
 'Drama',
 'Drama',
 'Sci-Fi',
 'Adventure',
 'Romance',
 "Children's",
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Drama',
 'Documentary',
 'Comedy',
 'Comedy',
 'Romance',
 'Drama',
 'Drama',
 'War',
 'Action',
 'Crime',
 'Drama',
 'Drama',
 'Action',
 'Adventure',
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Crime',
 'Thrill

In [160]:
genres = pd.unique(all_genres)

In [161]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [163]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [164]:
dummies = DataFrame(zero_matrix, columns=genres)

In [165]:
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [166]:
dummies

Animation  Children's  Comedy  ...  Mystery  Film-Noir  Western
0           0.0         0.0     0.0  ...      0.0        0.0      0.0
1           0.0         0.0     0.0  ...      0.0        0.0      0.0
2           0.0         0.0     0.0  ...      0.0        0.0      0.0
3           0.0         0.0     0.0  ...      0.0        0.0      0.0
4           0.0         0.0     0.0  ...      0.0        0.0      0.0
...         ...         ...     ...  ...      ...        ...      ...
3878        0.0         0.0     0.0  ...      0.0        0.0      0.0
3879        0.0         0.0     0.0  ...      0.0        0.0      0.0
3880        0.0         0.0     0.0  ...      0.0        0.0      0.0
3881        0.0         0.0     0.0  ...      0.0        0.0      0.0
3882        0.0         0.0     0.0  ...      0.0        0.0      0.0

[3883 rows x 18 columns]

In [167]:
gen = movies.genres[0]

In [168]:
gen

"Animation|Children's|Comedy"

In [169]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [170]:
dummies.columns

Index(['Animation', 'Children's', 'Comedy', 'Adventure', 'Fantasy', 'Romance',
       'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi',
       'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir', 'Western'],
      dtype='object')

In [171]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [172]:
gen2 = movies.genres[1]

In [174]:
dummies.columns.get_indexer(gen2.split('|'))

array([3, 1, 4])

In [175]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [176]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

movies_windic.iloc[0]

In [178]:
movies_windic

movie_id  ... Genre_Western
0            1  ...           0.0
1            2  ...           0.0
2            3  ...           0.0
3            4  ...           0.0
4            5  ...           0.0
...        ...  ...           ...
3878      3948  ...           0.0
3879      3949  ...           0.0
3880      3950  ...           0.0
3881      3951  ...           0.0
3882      3952  ...           0.0

[3883 rows x 21 columns]

In [179]:
dummies

Animation  Children's  Comedy  ...  Mystery  Film-Noir  Western
0           1.0         1.0     1.0  ...      0.0        0.0      0.0
1           0.0         1.0     0.0  ...      0.0        0.0      0.0
2           0.0         0.0     1.0  ...      0.0        0.0      0.0
3           0.0         0.0     1.0  ...      0.0        0.0      0.0
4           0.0         0.0     1.0  ...      0.0        0.0      0.0
...         ...         ...     ...  ...      ...        ...      ...
3878        0.0         0.0     1.0  ...      0.0        0.0      0.0
3879        0.0         0.0     0.0  ...      0.0        0.0      0.0
3880        0.0         0.0     0.0  ...      0.0        0.0      0.0
3881        0.0         0.0     0.0  ...      0.0        0.0      0.0
3882        0.0         0.0     0.0  ...      0.0        0.0      0.0

[3883 rows x 18 columns]

In [180]:
np.random.seed(12345)

In [181]:
values = np.random.rand(10)

In [182]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [183]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [184]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [185]:
val = 'a,b,  guido'

In [188]:
val.split(',')

['a', 'b', '  guido']

In [189]:
pieces = [x.strip() for x in val.split(',')]

In [190]:
pieces

['a', 'b', 'guido']

In [191]:
first, second, third = pieces

In [192]:
first + '::' + second + '::' + third

'a::b::guido'

In [193]:
'::'.join(pieces)

'a::b::guido'

In [194]:
'guido' in val

True

In [195]:
val.index(',')

1

In [196]:
val.index('guido')

6

In [197]:
val.find(':')

-1

In [198]:
val.index(':')

ValueError: substring not found

In [199]:
val.count(',')

2

In [200]:
val.replace(',', '::')

'a::b::  guido'

In [201]:
import re

In [203]:
text = "foo      bar\t baz    \tqux"

In [204]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [205]:
regex = re.compile('\s+')

In [206]:
regex

re.compile(r'\s+', re.UNICODE)

In [207]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [208]:
regex.findall(text)

['      ', '\t ', '    \t']

In [209]:
text = """
Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [213]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [214]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [215]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [216]:
m = regex.search(text)

In [217]:
m

<re.Match object; span=(6, 21), match='dave@google.com'>

In [218]:
text[m.start():m.end()]

'dave@google.com'

In [219]:
print(regex.match(text))

None


In [220]:
print(regex.sub('REDACTED', text))


Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [221]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [222]:
regex = re.compile(pattern, flags = re.IGNORECASE)

In [223]:
m = regex.match('wesm@bright.net')

In [224]:
m.groups()

('wesm', 'bright', 'net')

In [225]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [226]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))


Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [227]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [228]:
data = Series(data)

In [229]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [230]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [231]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [237]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [234]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [235]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [238]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [239]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [240]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN