In [1]:
from datetime import datetime

In [2]:
now = datetime.now()

In [3]:
now

datetime.datetime(2022, 7, 9, 20, 16, 44, 632136)

In [4]:
now.year, now.month, now.day

(2022, 7, 9)

In [5]:
delta = datetime(2011,1,7) - datetime(2008, 6, 24, 8, 15)

In [7]:
delta

datetime.timedelta(days=926, seconds=56700)

In [8]:
delta.days

926

In [9]:
delta.seconds

56700

In [10]:
from datetime import timedelta

In [11]:
start = datetime(2011, 1, 7)

In [12]:
start + timedelta(12)

datetime.datetime(2011, 1, 19, 0, 0)

In [13]:
start - 2 * timedelta(12)

datetime.datetime(2010, 12, 14, 0, 0)

In [14]:
stamp = datetime(2011, 1, 3)

In [15]:
str(stamp)

'2011-01-03 00:00:00'

In [16]:
stamp.strftime('%Y-%m-%d')

'2011-01-03'

In [17]:
value = '2011-01-03'

In [19]:
datetime.strptime(value, '%Y-%m-%d')

datetime.datetime(2011, 1, 3, 0, 0)

In [20]:
datestrs = ['7/6/2011', '8/6/2011']

In [21]:
[datetime.strptime(x, '%m/%d/%Y') for x in datestrs]

[datetime.datetime(2011, 7, 6, 0, 0), datetime.datetime(2011, 8, 6, 0, 0)]

In [22]:
from dateutil.parser import parse

In [23]:
parse('2011-01-03')

datetime.datetime(2011, 1, 3, 0, 0)

In [24]:
parse('Jan 31, 1997 10:45 PM')

datetime.datetime(1997, 1, 31, 22, 45)

In [25]:
parse('6/12/2011', dayfirst=True)

datetime.datetime(2011, 12, 6, 0, 0)

In [26]:
datestrs = ['2011-07-06 12:00:00', '2011-08-06 00:00:00']

In [28]:
import pandas as pd
pd.to_datetime(datestrs)

DatetimeIndex(['2011-07-06 12:00:00', '2011-08-06 00:00:00'], dtype='datetime64[ns]', freq=None)

In [29]:
idx = pd.to_datetime(datestrs + [None])

In [30]:
idx

DatetimeIndex(['2011-07-06 12:00:00', '2011-08-06 00:00:00', 'NaT'], dtype='datetime64[ns]', freq=None)

In [31]:
idx[2]

NaT

In [32]:
pd.isnull(idx)

array([False, False,  True])

In [33]:
dates = [datetime(2011,1,2),datetime(2011,1,5), datetime(2011,1,7), datetime(2011,1,8), datetime(2011,1,10), datetime(2011,1,12)]

In [34]:
from pandas import Series, DataFrame

In [35]:
import numpy as np

In [36]:
ts = Series(np.random.randn(6), index=dates)

In [38]:
ts

2011-01-02    2.973291
2011-01-05   -0.693859
2011-01-07    1.720622
2011-01-08   -1.592766
2011-01-10   -0.458432
2011-01-12   -1.096808
dtype: float64

In [39]:
ts.index

DatetimeIndex(['2011-01-02', '2011-01-05', '2011-01-07', '2011-01-08',
               '2011-01-10', '2011-01-12'],
              dtype='datetime64[ns]', freq=None)

In [40]:
ts + ts[::2]

2011-01-02    5.946581
2011-01-05         NaN
2011-01-07    3.441244
2011-01-08         NaN
2011-01-10   -0.916864
2011-01-12         NaN
dtype: float64

In [41]:
ts.index.dtype

dtype('<M8[ns]')

In [42]:
stamp = ts.index[0]

In [43]:
stamp

Timestamp('2011-01-02 00:00:00')

In [44]:
stamp = ts.index[2]

In [45]:
ts[stamp]

1.720622133426416

In [46]:
ts['1/10/2011']

-0.4584320721851953

In [47]:
ts['20110110']

-0.4584320721851953

In [49]:
longer_ts = Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))

In [50]:
longer_ts

2000-01-01   -0.829328
2000-01-02   -1.073655
2000-01-03    0.151852
2000-01-04    0.680791
2000-01-05    2.602603
                ...   
2002-09-22    1.303910
2002-09-23   -0.902917
2002-09-24    0.255336
2002-09-25    0.122862
2002-09-26    0.367223
Freq: D, Length: 1000, dtype: float64

In [51]:
longer_ts['2001']

2001-01-01   -0.054351
2001-01-02    0.568789
2001-01-03    0.125482
2001-01-04   -2.182706
2001-01-05    0.996150
                ...   
2001-12-27   -1.638733
2001-12-28    1.146635
2001-12-29    1.347980
2001-12-30   -0.340102
2001-12-31    1.049462
Freq: D, Length: 365, dtype: float64

In [52]:
longer_ts['2001-05']

2001-05-01    0.443962
2001-05-02    0.804707
2001-05-03   -0.137096
2001-05-04    0.446047
2001-05-05    0.425682
2001-05-06    0.181419
2001-05-07    0.623741
2001-05-08   -0.122099
2001-05-09    0.840915
2001-05-10   -0.288583
2001-05-11   -0.824813
2001-05-12    0.254092
2001-05-13    0.604281
2001-05-14    1.579789
2001-05-15   -0.563921
2001-05-16   -0.878807
2001-05-17    1.507318
2001-05-18   -0.693852
2001-05-19    2.323834
2001-05-20    1.826891
2001-05-21    0.548079
2001-05-22    1.481989
2001-05-23    0.775263
2001-05-24    0.323786
2001-05-25    1.017815
2001-05-26   -1.043171
2001-05-27    0.827185
2001-05-28   -0.145541
2001-05-29    1.210776
2001-05-30    0.569037
2001-05-31   -0.562869
Freq: D, dtype: float64

In [53]:
ts[datetime(2011,1,7)]

1.720622133426416

In [54]:
ts

2011-01-02    2.973291
2011-01-05   -0.693859
2011-01-07    1.720622
2011-01-08   -1.592766
2011-01-10   -0.458432
2011-01-12   -1.096808
dtype: float64

In [55]:
ts['1/6/2011':'1/11/2011']

2011-01-07    1.720622
2011-01-08   -1.592766
2011-01-10   -0.458432
dtype: float64

In [56]:
ts.truncate(after='1/9/2011')

2011-01-02    2.973291
2011-01-05   -0.693859
2011-01-07    1.720622
2011-01-08   -1.592766
dtype: float64

In [57]:
dates  =pd.date_range('1/1/2000', periods=100, freq='W-WED')

In [58]:
long_df = DataFrame(np.random.randn(100,4), index=dates, columns=['Colorado', 'Texas', 'New York','Ohio'])

In [59]:
long_df.loc['5-2001']

Colorado     Texas  New York      Ohio
2001-05-02  0.462541  1.586178 -0.343723  1.292704
2001-05-09 -0.656591 -0.323540 -0.423422  0.536117
2001-05-16 -0.966332  1.299535 -1.368470 -0.653069
2001-05-23 -0.218466  1.225634 -1.648858 -0.122108
2001-05-30  0.101070 -0.051705 -1.572876 -0.571850

In [60]:
dates = pd.DatetimeIndex(['1/1/2000', '1/2/2000', '1/2/2000',  '1/2/2000', '1/3/2000'])

In [61]:
dup_ts = Series(np.arange(5), index=dates)

In [62]:
dup_ts

2000-01-01    0
2000-01-02    1
2000-01-02    2
2000-01-02    3
2000-01-03    4
dtype: int64

In [63]:
dup_ts.is_unique

True

In [64]:
dup_ts.index.is_unique

False

In [65]:
dup_ts['1/3/2000']

4

In [66]:
dup_ts['1/2/2000']

2000-01-02    1
2000-01-02    2
2000-01-02    3
dtype: int64

In [67]:
grouped = dup_ts.groupby(level=0)

In [68]:
grouped.mean()

2000-01-01    0.0
2000-01-02    2.0
2000-01-03    4.0
dtype: float64

In [69]:
grouped.count()

2000-01-01    1
2000-01-02    3
2000-01-03    1
dtype: int64

In [70]:
ts

2011-01-02    2.973291
2011-01-05   -0.693859
2011-01-07    1.720622
2011-01-08   -1.592766
2011-01-10   -0.458432
2011-01-12   -1.096808
dtype: float64

In [72]:
resampler = ts.resample('D')

In [73]:
resampler

In [74]:
index = pd.date_range('2012-04-01', '2012-06-01')

In [75]:
index

DatetimeIndex(['2012-04-01', '2012-04-02', '2012-04-03', '2012-04-04',
               '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
               '2012-04-09', '2012-04-10', '2012-04-11', '2012-04-12',
               '2012-04-13', '2012-04-14', '2012-04-15', '2012-04-16',
               '2012-04-17', '2012-04-18', '2012-04-19', '2012-04-20',
               '2012-04-21', '2012-04-22', '2012-04-23', '2012-04-24',
               '2012-04-25', '2012-04-26', '2012-04-27', '2012-04-28',
               '2012-04-29', '2012-04-30', '2012-05-01', '2012-05-02',
               '2012-05-03', '2012-05-04', '2012-05-05', '2012-05-06',
               '2012-05-07', '2012-05-08', '2012-05-09', '2012-05-10',
               '2012-05-11', '2012-05-12', '2012-05-13', '2012-05-14',
               '2012-05-15', '2012-05-16', '2012-05-17', '2012-05-18',
               '2012-05-19', '2012-05-20', '2012-05-21', '2012-05-22',
               '2012-05-23', '2012-05-24', '2012-05-25', '2012-05-26',
      

In [76]:
pd.date_range(start='2012-04-01', periods=20)

DatetimeIndex(['2012-04-01', '2012-04-02', '2012-04-03', '2012-04-04',
               '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
               '2012-04-09', '2012-04-10', '2012-04-11', '2012-04-12',
               '2012-04-13', '2012-04-14', '2012-04-15', '2012-04-16',
               '2012-04-17', '2012-04-18', '2012-04-19', '2012-04-20'],
              dtype='datetime64[ns]', freq='D')

In [77]:
pd.date_range(end='2012-06-01', periods=20)

DatetimeIndex(['2012-05-13', '2012-05-14', '2012-05-15', '2012-05-16',
               '2012-05-17', '2012-05-18', '2012-05-19', '2012-05-20',
               '2012-05-21', '2012-05-22', '2012-05-23', '2012-05-24',
               '2012-05-25', '2012-05-26', '2012-05-27', '2012-05-28',
               '2012-05-29', '2012-05-30', '2012-05-31', '2012-06-01'],
              dtype='datetime64[ns]', freq='D')

In [78]:
pd.date_range('2000-01-01', '2000-12-01', freq='BM')

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-28',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31',
               '2000-09-29', '2000-10-31', '2000-11-30'],
              dtype='datetime64[ns]', freq='BM')

In [79]:
pd.date_range('2012-05-02 12:56:31', periods=5)

DatetimeIndex(['2012-05-02 12:56:31', '2012-05-03 12:56:31',
               '2012-05-04 12:56:31', '2012-05-05 12:56:31',
               '2012-05-06 12:56:31'],
              dtype='datetime64[ns]', freq='D')

In [80]:
pd.date_range('2012-05-02 12:56:31', periods = 5, normalize=True)

DatetimeIndex(['2012-05-02', '2012-05-03', '2012-05-04', '2012-05-05',
               '2012-05-06'],
              dtype='datetime64[ns]', freq='D')

In [81]:
from pandas.tseries.offsets import Hour, Minute

In [82]:
hour = Hour()

In [83]:
hour

<Hour>

In [84]:
four_hours = Hour(4)

In [85]:
four_hours

<4 * Hours>

In [86]:
pd.date_range('2000-01-01', '2001-01-03 23:59', freq='4h')

DatetimeIndex(['2000-01-01 00:00:00', '2000-01-01 04:00:00',
               '2000-01-01 08:00:00', '2000-01-01 12:00:00',
               '2000-01-01 16:00:00', '2000-01-01 20:00:00',
               '2000-01-02 00:00:00', '2000-01-02 04:00:00',
               '2000-01-02 08:00:00', '2000-01-02 12:00:00',
               ...
               '2001-01-02 08:00:00', '2001-01-02 12:00:00',
               '2001-01-02 16:00:00', '2001-01-02 20:00:00',
               '2001-01-03 00:00:00', '2001-01-03 04:00:00',
               '2001-01-03 08:00:00', '2001-01-03 12:00:00',
               '2001-01-03 16:00:00', '2001-01-03 20:00:00'],
              dtype='datetime64[ns]', length=2214, freq='4H')

In [87]:
Hour(2) + Minute(30)

<150 * Minutes>

In [88]:
pd.date_range('2000-01-01', periods=10, freq='1h30min')

DatetimeIndex(['2000-01-01 00:00:00', '2000-01-01 01:30:00',
               '2000-01-01 03:00:00', '2000-01-01 04:30:00',
               '2000-01-01 06:00:00', '2000-01-01 07:30:00',
               '2000-01-01 09:00:00', '2000-01-01 10:30:00',
               '2000-01-01 12:00:00', '2000-01-01 13:30:00'],
              dtype='datetime64[ns]', freq='90T')

In [89]:
rng = pd.date_range('2012-01-01', '2012-09-01', freq='WOM-3FRI')

In [90]:
list(rng)

[Timestamp('2012-01-20 00:00:00', freq='WOM-3FRI'),
 Timestamp('2012-02-17 00:00:00', freq='WOM-3FRI'),
 Timestamp('2012-03-16 00:00:00', freq='WOM-3FRI'),
 Timestamp('2012-04-20 00:00:00', freq='WOM-3FRI'),
 Timestamp('2012-05-18 00:00:00', freq='WOM-3FRI'),
 Timestamp('2012-06-15 00:00:00', freq='WOM-3FRI'),
 Timestamp('2012-07-20 00:00:00', freq='WOM-3FRI'),
 Timestamp('2012-08-17 00:00:00', freq='WOM-3FRI')]

In [91]:
ts = pd.Series(np.random.randn(4), index=pd.date_range('1/1/2000', periods=4, freq='M'))

In [92]:
ts

2000-01-31   -0.337753
2000-02-29   -0.719657
2000-03-31    0.448032
2000-04-30   -0.550554
Freq: M, dtype: float64

In [93]:
ts.shift(2)

2000-01-31         NaN
2000-02-29         NaN
2000-03-31   -0.337753
2000-04-30   -0.719657
Freq: M, dtype: float64

In [94]:
ts.shift(-2)

2000-01-31    0.448032
2000-02-29   -0.550554
2000-03-31         NaN
2000-04-30         NaN
Freq: M, dtype: float64

In [95]:
ts / ts.shift(1) -1

2000-01-31         NaN
2000-02-29    1.130716
2000-03-31   -1.622563
2000-04-30   -2.228829
Freq: M, dtype: float64

In [96]:
ts.shift(2, freq='M')

2000-03-31   -0.337753
2000-04-30   -0.719657
2000-05-31    0.448032
2000-06-30   -0.550554
Freq: M, dtype: float64

In [97]:
ts.shift(3, freq='D')

2000-02-03   -0.337753
2000-03-03   -0.719657
2000-04-03    0.448032
2000-05-03   -0.550554
dtype: float64

In [98]:
ts.shift(1, freq='90T')

2000-01-31 01:30:00   -0.337753
2000-02-29 01:30:00   -0.719657
2000-03-31 01:30:00    0.448032
2000-04-30 01:30:00   -0.550554
dtype: float64

In [100]:
from pandas.tseries.offsets import Day, MonthEnd

In [101]:
now = datetime(2011,11,17)

In [102]:
now + 3  * Day()

Timestamp('2011-11-20 00:00:00')

In [103]:
now + MonthEnd()

Timestamp('2011-11-30 00:00:00')

In [104]:
now + MonthEnd(2)

Timestamp('2011-12-31 00:00:00')

In [105]:
offset = MonthEnd()

In [106]:
offset.rollforward(now)

Timestamp('2011-11-30 00:00:00')

In [299]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 4

In [301]:
N = len(fruits)

In [302]:
df = DataFrame({'fruit': fruits, 'basket_id': np.arange(N), 'count': np.random.randint(3, 15, size=N), 'weight': np.random.uniform(0, 4, size=N)}, columns=['basket_id', 'fruit', 'count', 'weight'])

In [303]:
df

basket_id   fruit  count    weight
0           0   apple     13  3.708485
1           1  orange     12  2.985767
2           2   apple      6  1.680193
3           3   apple     13  3.614156
4           4   apple      6  2.650830
5           5  orange      7  1.272172
6           6   apple     13  0.777652
7           7   apple     11  3.821171
8           8   apple      4  1.418221
9           9  orange      6  3.223873
10         10   apple     11  0.784802
11         11   apple      4  1.461828
12         12   apple      6  1.614938
13         13  orange      5  2.289702
14         14   apple     11  0.429022
15         15   apple      5  1.994141

In [304]:
fruit_cat = df['fruit'].astype('category')

In [305]:
fruit_cat

0      apple
1     orange
2      apple
3      apple
4      apple
5     orange
6      apple
7      apple
8      apple
9     orange
10     apple
11     apple
12     apple
13    orange
14     apple
15     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [306]:
c = fruit_cat.values

In [307]:
type(c)

pandas.core.arrays.categorical.Categorical

In [308]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [309]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [310]:
df['fruit'] = df['fruit'].astype('category')

In [311]:
df.fruit

0      apple
1     orange
2      apple
3      apple
4      apple
5     orange
6      apple
7      apple
8      apple
9     orange
10     apple
11     apple
12     apple
13    orange
14     apple
15     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [312]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [313]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [314]:
categories = ['foo', 'bar', 'baz']

In [315]:
codes = [0,1,2,0,0,1]

In [316]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [317]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [318]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [319]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [320]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [321]:
np.random.seed(12345)

In [322]:
draws = np.random.randn(1000)

In [323]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [324]:
bins = pd.qcut(draws, 4)

In [325]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [326]:
bins = pd.qcut(draws, 4, labels =['Q1', 'Q2', 'Q3','Q4'])

In [327]:
bins

['Q2', 'Q3', 'Q2', 'Q2', 'Q4', ..., 'Q3', 'Q2', 'Q1', 'Q3', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [328]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [329]:
bins = Series(bins, name='quartile')

In [330]:
results = (Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())

In [331]:
results

quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [332]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [333]:
N = 10000000

In [334]:
draws = Series(np.random.randn(N))

In [335]:
labels  = Series(['foo', 'bar', 'baz', 'qux'] * (N//4))

In [336]:
categories  = labels.astype('category')

In [337]:
labels.memory_usage()

80000128

In [338]:
categories.memory_usage()

10000332

In [339]:
%time _ = labels.astype('category')

CPU times: user 376 ms, sys: 31.7 ms, total: 408 ms
Wall time: 408 ms


In [340]:
s = Series(['a', 'b', 'c', 'd'] * 2)

In [341]:
cat_s = s.astype('category')

In [342]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [343]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [344]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [345]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [346]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [347]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [348]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64