In [13]:
import pandas as pd

In [14]:
from pandas import Series, DataFrame

In [15]:
obj = pd.Series([4,7,-5,3])

In [16]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [17]:
obj.values

array([ 4,  7, -5,  3])

In [18]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])

In [20]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [21]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [22]:
obj2['a']

-5

In [23]:
obj2['d'] = 6

In [24]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [25]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [26]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [27]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [28]:
'b' in obj2

True

In [29]:
'e' in obj2

False

In [30]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000,  'Utah': 5000}

In [31]:
obj3= Series(sdata)

In [32]:
obj3 

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
states  = {'California', 'Ohio', 'Oregon', 'Texas'}

In [34]:
obj4 = Series(sdata, index=states)

In [35]:
obj4

Texas         71000.0
Ohio          35000.0
California        NaN
Oregon        16000.0
dtype: float64

In [36]:
pd.isnull(obj4)

Texas         False
Ohio          False
California     True
Oregon        False
dtype: bool

In [37]:
pd.notnull(obj4)

Texas          True
Ohio           True
California    False
Oregon         True
dtype: bool

In [38]:
obj4.isnull()

Texas         False
Ohio          False
California     True
Oregon        False
dtype: bool

In [41]:
obj4.notnull()

Texas          True
Ohio           True
California    False
Oregon         True
dtype: bool

In [42]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [43]:
obj4

Texas         71000.0
Ohio          35000.0
California        NaN
Oregon        16000.0
dtype: float64

In [44]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [45]:
obj4.name = 'population'

In [46]:
obj4.index.name= 'state'

In [47]:
obj4

state
Texas         71000.0
Ohio          35000.0
California        NaN
Oregon        16000.0
Name: population, dtype: float64

In [48]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [49]:
obj.index =  ['Bob', 'Steve', 'Jeff', 'Ryan']

In [50]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [51]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000,2001,2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [52]:
frame = DataFrame(data)

In [53]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [54]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [55]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [56]:
frame2 = DataFrame(data, columns = ['year', 'state',  'pop',  'debt'],  index=['one', 'two', 'three','four', 'five', 'six'])

In [57]:
frame2 

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [59]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [60]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [61]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [62]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [63]:
frame2['debt'] = 16.5

In [64]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [65]:
frame2['debt'] = np.arange(6.)

In [66]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [67]:
val = Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

In [68]:
frame2['debt'] =val

In [69]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [70]:
frame2['eastern'] = frame2.state == 'Ohio'

In [71]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [72]:
del frame2['eastern']

In [73]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [74]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [75]:
frame3 =DataFrame(pop)

In [76]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [77]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [78]:
DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [79]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada':  frame3['Nevada'][:2]}

In [80]:
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [81]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [82]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [83]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [84]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [85]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [87]:
index = obj.index

In [88]:
index

Index(['a', 'b', 'c'], dtype='object')

In [89]:
index[1:]

Index(['b', 'c'], dtype='object')

In [90]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [91]:
labels = pd.Index(np.arange(3))

In [92]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [93]:
obj2 = Series([1.5,-.25, 0], index=labels)

In [94]:
obj2

0    1.50
1   -0.25
2    0.00
dtype: float64

In [97]:
obj2.index is labels

True

In [98]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [99]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [100]:
'Ohio' in frame3.columns

True

In [101]:
2003 in frame3.index

False

In [102]:
dup_labels  = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [103]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [104]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [105]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [106]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [107]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [108]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [109]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [110]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [111]:
frame = DataFrame(np.arange(9).reshape((3,3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [112]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [113]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [114]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [115]:
states = ['Texas', 'Utah', 'California']

In [116]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [117]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['b'] not in index"

In [118]:
obj = Series(np.arange(5.), index=['a' ,'b', 'c', 'd', 'e'])

In [119]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [120]:
new_obj = obj.drop('c')

In [121]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [122]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [123]:
data = DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [124]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [129]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [130]:
obj.drop('c', inplace=True)

In [131]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [132]:
obj.drop('c')

KeyError: "['c'] not found in axis"

In [134]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [135]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [136]:
obj['b']

1.0

In [137]:
obj[1]

1.0

In [138]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [139]:
obj[['b','a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [140]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [141]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [142]:
obj['b': 'c']

b    1.0
c    2.0
dtype: float64

In [143]:
obj['b': 'c'] = 5

In [144]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [145]:
data = DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns = ['one', 'two', 'three', 'four'])

In [146]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [147]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [148]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [149]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [150]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [151]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False