In [1]:
import statsmodels

In [2]:
import statsmodels.api as sm

In [4]:
import statsmodels.formula.api as smt
import numpy as  np

In [19]:
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * np.random.randn(*size)

In [6]:
np.random.seed(12345)

In [7]:
init_x = 4

In [8]:
import random

In [9]:
values = [init_x, init_x]

In [10]:
N = 1000

In [11]:
b0 = 0.8

In [12]:
b1 = -0.4

In [20]:
noise = dnorm(0, 0.1, N)

In [22]:
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

In [23]:
MAXLAGS = 5

In [24]:
model = sm.tsa.AR(values)

NotImplementedError: AR has been removed from statsmodels and replaced with statsmodels.tsa.ar_model.AutoReg.

In [28]:
model = statsmodels.tsa.ar_model.AutoReg(values, [1,5])

In [29]:
model

In [31]:
model.params

AttributeError: 'AutoReg' object has no attribute 'params'

In [32]:
model?

In [33]:
model.params

AttributeError: 'AutoReg' object has no attribute 'params'

In [35]:
import pandas as pd
train = pd.read_csv('datasets/titanic/train.csv')

In [36]:
test  = pd.read_csv('datasets/titanic/test.csv')

In [37]:
train[:4]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [39]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [40]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [41]:
impute_value   = train['Age'].median()

In [42]:
train['Age'] = train['Age'].fillna(impute_value)

In [43]:
test['Age'] = test['Age'].fillna(impute_value)

In [44]:
train['IsFemale'] = (train['Sex'] == 'female').astype(int)

In [45]:
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [46]:
test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0      male  34.5      0      0              330911    7.8292   NaN        Q   
1    female  47.0      1      0              363272    7.0000   NaN        S   
2      male  62.0      0      0              240276    9.6875   NaN        Q   
3      male  27.0      0      0              315154    8.6625   NaN        S   
4    female  22.0      1      1             3101298   12.2875   NaN        S   
..      ...   ...    ...    ...                 ...       ...   ...      ...   
413    male  28.0      0      0           A.5. 3236    8.0500   NaN        S   
414  female  39.0      0      0            PC 17758  108.9000  C105        C   
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S   
416    male  28.0      0      0              359309    8.0500   NaN        S   
417    male  28.0      1      1                2668   22.3583   NaN        C   

     IsFemale  
0           0  
1           1  
2           0  
3           0  
4           1  
..        ...  
413         0  
414         1  
415         0  
416         0  
417         0  

[418 rows x 12 columns]

In [47]:
predictors = ['Pclass', 'IsFemale', 'Age']
X_train = train[predictors].values

In [48]:
X_test = test[predictors].values

In [49]:
y_train = train['Survived'].values

In [50]:
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [51]:
y_train[:5]

array([0, 1, 1, 1, 0])

In [53]:
from sklearn.linear_model import LogisticRegression

In [54]:
model = LogisticRegression()

In [55]:
model.fit(X_train, y_train)

LogisticRegression()

In [56]:
y_predict = model.predict(X_test)

In [57]:
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [58]:
from sklearn.linear_model import LogisticRegressionCV

In [60]:
model_cv = LogisticRegressionCV()

In [61]:
model_cv.fit(X_train, y_train)

LogisticRegressionCV()

In [62]:
from sklearn.model_selection import cross_val_score

In [63]:
model = LogisticRegression(C=10)

In [64]:
scores = cross_val_score(model, X_train, y_train, cv=4)

In [65]:
scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])