<a href="https://colab.research.google.com/github/janShi1105/science/blob/main/ML14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import tensorflow as tf

In [36]:
g = tf.Graph()

In [37]:
with g.as_default():
  a = tf.constant(1, name='a')
  b = tf.constant(2, name='b')
  c = tf.constant(3, name='c')
  z = 2 * (a-b) + c

In [38]:
with tf.compat.v1.Session(graph=g) as sess:
  print('Result: z = ', sess.run(z))

Result: z =  1


In [39]:
a = tf.constant(1, name='a')
b = tf.constant(2, name='b')
c = tf.constant(3, name='c')
z = 2*(a-b) + c
tf.print('Result: z= ', z)

Result: z=  1


In [40]:
g = tf.Graph()
with g.as_default():
  a = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_a')
  b = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_b')
  c = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_c')
  z = 2 * (a-b) + c

  with tf.compat.v1.Session(graph=g) as sess:
    feed_dict = {a:1, b:2, c:3}
    print('Result: z = ', sess.run(z, feed_dict=feed_dict))

Result: z =  1


In [41]:
def compute_z(a,b,c):
  r1 = tf.subtract(a,b)
  r2 = tf.multiply(2, r1)
  z= tf.add(r2, c)
  return z
  

In [42]:
tf.print('Scaler Inputs: ', compute_z(1,2,3))

Scaler Inputs:  1


In [43]:
tf.print('Rank 1 Inputs: ', compute_z([1], [2], [3]))

Rank 1 Inputs:  [1]


In [44]:
tf.print('Rank 2 Inputs: ', compute_z([[1]], [[2]], [[3]]))

Rank 2 Inputs:  [[1]]


In [45]:
@tf.function
def compute_z(a,b,c):
  r1 = tf.subtract(a,b)
  r2 = tf.multiply(2, r1)
  z= tf.add(r2, c)
  return z
  

In [46]:
tf.print('Scaler Inputs: ', compute_z(1,2,3))

Scaler Inputs:  1


In [47]:
tf.print('Rank 1 Inputs: ', compute_z([1], [2], [3]))

Rank 1 Inputs:  [1]


In [48]:
tf.print('Rank 2 Inputs: ', compute_z([[1]], [[2]], [[3]]))

Rank 2 Inputs:  [[1]]


In [49]:
@tf.function(input_signature=(tf.TensorSpec(shape=[None], dtype=tf.int32), tf.TensorSpec(shape=[None], dtype=tf.int32), tf.TensorSpec(shape=[None], dtype=tf.int32),))
def compute_z(a,b,c):
  r1 = tf.subtract(a,b)
  r2 = tf.multiply(2, r1)
  z= tf.add(r2, c)
  return z

ValueError: ignored

In [51]:
tf.print('Rank 1 Inputs: ', compute_z([1], [2], [3]))

Rank 1 Inputs:  [1]


In [52]:
tf.print('Rank 1 Inputs: ', compute_z([1,2], [2,4], [3,6]))

Rank 1 Inputs:  [1 2]


In [53]:
a = tf.Variable(initial_value=3.14, name='var_a')
print(a)

<tf.Variable 'var_a:0' shape=() dtype=float32, numpy=3.14>


In [54]:
b = tf.Variable(initial_value=[1,2,3], name='var_b')
print(b)

<tf.Variable 'var_b:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [55]:
c = tf.Variable(initial_value=[True, False], dtype=tf.bool)
print(c)

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>


In [56]:
d = tf.Variable(initial_value=['abc'], dtype=tf.string)

In [57]:
print(d)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'abc'], dtype=object)>


In [58]:
w = tf.Variable([1,2,3], trainable=False)
print(w.trainable)

False


In [59]:
print(w.assign([3,1,4], read_value=True))

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 1, 4], dtype=int32)>


In [60]:
w.assign_add([2,-1,2], read_value=False)
print(w.value())

tf.Tensor([5 0 6], shape=(3,), dtype=int32)


In [61]:
tf.random.set_seed(1)
init = tf.keras.initializers.GlorotNormal()
tf.print(init(shape=(3,)))

[-0.722795904 1.01456821 0.251808226]


In [62]:
v = tf.Variable(init(shape=(2,3)))
tf.print(v)

[[0.28982234 -0.782292783 -0.0453658961]
 [0.960991383 -0.120003454 0.708528221]]


In [63]:
class MyModule(tf.Module):
  def __init__(self):
    init = tf.keras.initializers.GlorotNormal()
    self.w1 = tf.Variable(init(shape=(2,3)), trainable=True)
    self.w2 = tf.Variable(init(shape=(1,2)), trainable=False)

m = MyModule()
print('All module variables: ', [v.shape for v in m.variables])

All module variables:  [TensorShape([2, 3]), TensorShape([1, 2])]


In [64]:
print('Trainable variable: ', [v.shape for v in m.trainable_variables])

Trainable variable:  [TensorShape([2, 3])]


In [65]:
tf.random.set_seed(1)

w = tf.Variable(tf.random.uniform((3,3)))
@tf.function
def compute_z(x):
  return tf.matmul(w,x)

x = tf.Variable([[1], [2], [3]], dtype=tf.float32)
tf.print(compute_z(x))

[[3.8610158]
 [2.94593048]
 [3.82629013]]


In [66]:
w = tf.Variable(1.0)
b = tf.Variable(0.5)


In [70]:
print(w.trainable, b.trainable)

x= tf.convert_to_tensor([1.4])
y = tf.convert_to_tensor([2.1])
with tf.GradientTape() as tape:
  z = tf.add(tf.multiply(w, x), b)
  loss = tf.reduce_sum(tf.square(y -z ))

dloss_dw = tape.gradient(loss, w)
tf.print('dL/dw:', dloss_dw)

True True
dL/dw: -0.559999764


In [71]:
tf.print(2*x*(w*x+b-y))

[-0.559999764]


In [74]:
with tf.GradientTape() as tape:
  tape.watch(x)
  z = tf.add(tf.multiply(w, x), b)
  loss = tf.reduce_sum(tf.square(y- z))

dloss_dx = tape.gradient(loss, x)
tf.print('dL/dx:', dloss_dx)

dL/dx: [-0.399999857]


In [75]:
with tf.GradientTape(persistent=True) as tape:
  z = tf.add(tf.multiply(w,x), b)
  loss = tf.reduce_sum(tf.square(y - z))

  dloss_dw = tape.gradient(loss, w)
  tf.print('dL/dw:', dloss_dw)

  dloss_db = tape.gradient(loss, b)
  tf.print('dL/db:', dloss_db)

dL/dw: -0.559999764


dL/db: -0.399999857


In [78]:
optimizer = tf.keras.optimizers.SGD()
optimizer.apply_gradients(zip([dloss_dw, dloss_db], [w,b]))
tf.print('Updated w: ', w)
tf.print('Updated b:', b)
tf.print(dloss_dw)
tf.print(dloss_db)

Updated w:  1.0112
Updated b: 0.508
-0.559999764
-0.399999857


In [80]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=16, activation='relu'))
model.add(tf.keras.layers.Dense(units=32, activation='relu'))
model.build(input_shape=(None, 4))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 16)                80        
                                                                 
 dense_3 (Dense)             (None, 32)                544       
                                                                 
Total params: 624
Trainable params: 624
Non-trainable params: 0
_________________________________________________________________


In [81]:
for v in model.variables:
  print('{:20s}'.format(v.name), v.trainable, v.shape)

dense_2/kernel:0     True (4, 16)
dense_2/bias:0       True (16,)
dense_3/kernel:0     True (16, 32)
dense_3/bias:0       True (32,)


In [82]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=16, activation=tf.keras.activations.relu, kernel_initializer=tf.keras.initializers.glorot_uniform(), 
                                bias_initializer=tf.keras.initializers.Constant(2.0)))
model.add(tf.keras.layers.Dense(units=32, activation=tf.keras.activations.sigmoid, kernel_regularizer=tf.keras.regularizers.l1))