<a href="https://colab.research.google.com/github/janShi1105/science/blob/main/ML14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
g = tf.Graph()

In [3]:
with g.as_default():
  a = tf.constant(1, name='a')
  b = tf.constant(2, name='b')
  c = tf.constant(3, name='c')
  z = 2 * (a-b) + c

In [4]:
with tf.compat.v1.Session(graph=g) as sess:
  print('Result: z = ', sess.run(z))

Result: z =  1


In [5]:
a = tf.constant(1, name='a')
b = tf.constant(2, name='b')
c = tf.constant(3, name='c')
z = 2*(a-b) + c
tf.print('Result: z= ', z)

Result: z=  1


In [6]:
g = tf.Graph()
with g.as_default():
  a = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_a')
  b = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_b')
  c = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_c')
  z = 2 * (a-b) + c

  with tf.compat.v1.Session(graph=g) as sess:
    feed_dict = {a:1, b:2, c:3}
    print('Result: z = ', sess.run(z, feed_dict=feed_dict))

Result: z =  1


In [7]:
def compute_z(a,b,c):
  r1 = tf.subtract(a,b)
  r2 = tf.multiply(2, r1)
  z= tf.add(r2, c)
  return z
  

In [8]:
tf.print('Scaler Inputs: ', compute_z(1,2,3))

Scaler Inputs:  1


In [9]:
tf.print('Rank 1 Inputs: ', compute_z([1], [2], [3]))

Rank 1 Inputs:  [1]


In [11]:
tf.print('Rank 2 Inputs: ', compute_z([[1]], [[2]], [[3]]))

Rank 2 Inputs:  [[1]]


In [12]:
@tf.function
def compute_z(a,b,c):
  r1 = tf.subtract(a,b)
  r2 = tf.multiply(2, r1)
  z= tf.add(r2, c)
  return z
  

In [13]:
tf.print('Scaler Inputs: ', compute_z(1,2,3))

Scaler Inputs:  1


In [14]:
tf.print('Rank 1 Inputs: ', compute_z([1], [2], [3]))

Rank 1 Inputs:  [1]


In [15]:
tf.print('Rank 2 Inputs: ', compute_z([[1]], [[2]], [[3]]))

Rank 2 Inputs:  [[1]]


In [16]:
@tf.function(input_signature=(tf.TensorSpec(shape=[None], dtype=tf.int32), tf.TensorSpec(shape=[None], dtype=tf.int32), tf.TensorSpec(shape=[None], dtype=tf.int32),))
def compute_z(a,b,c):
  r1 = tf.subtract(a,b)
  r2 = tf.multiply(2, r1)
  z= tf.add(r2, c)
  return z

In [17]:
tf.print('Scaler Inputs: ', compute_z(1,2,3))

ValueError: ignored

In [18]:
tf.print('Rank 1 Inputs: ', compute_z([1], [2], [3]))

Rank 1 Inputs:  [1]


In [19]:
tf.print('Rank 1 Inputs: ', compute_z([1,2], [2,4], [3,6]))

Rank 1 Inputs:  [1 2]


In [20]:
a = tf.Variable(initial_value=3.14, name='var_a')
print(a)

<tf.Variable 'var_a:0' shape=() dtype=float32, numpy=3.14>


In [21]:
b = tf.Variable(initial_value=[1,2,3], name='var_b')
print(b)

<tf.Variable 'var_b:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [22]:
c = tf.Variable(initial_value=[True, False], dtype=tf.bool)
print(c)

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>


In [23]:
d = tf.Variable(initial_value=['abc'], dtype=tf.string)

In [24]:
print(d)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'abc'], dtype=object)>


In [25]:
w = tf.Variable([1,2,3], trainable=False)
print(w.trainable)

False


In [26]:
print(w.assign([3,1,4], read_value=True))

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 1, 4], dtype=int32)>


In [27]:
w.assign_add([2,-1,2], read_value=False)
print(w.value())

tf.Tensor([5 0 6], shape=(3,), dtype=int32)


In [28]:
tf.random.set_seed(1)
init = tf.keras.initializers.GlorotNormal()
tf.print(init(shape=(3,)))

[-0.722795904 1.01456821 0.251808226]


In [29]:
v = tf.Variable(init(shape=(2,3)))
tf.print(v)

[[0.28982234 -0.782292783 -0.0453658961]
 [0.960991383 -0.120003454 0.708528221]]


In [30]:
class MyModule(tf.Module):
  def __init__(self):
    init = tf.keras.initializers.GlorotNormal()
    self.w1 = tf.Variable(init(shape=(2,3)), trainable=True)
    self.w2 = tf.Variable(init(shape=(1,2)), trainable=False)

m = MyModule()
print('All module variables: ', [v.shape for v in m.variables])

All module variables:  [TensorShape([2, 3]), TensorShape([1, 2])]


In [31]:
print('Trainable variable: ', [v.shape for v in m.trainable_variables])

Trainable variable:  [TensorShape([2, 3])]


In [33]:
tf.random.set_seed(1)

w = tf.Variable(tf.random.uniform((3,3)))
@tf.function
def compute_z(x):
  return tf.matmul(w,x)

x = tf.Variable([[1], [2], [3]], dtype=tf.float32)
tf.print(compute_z(x))

[[3.8610158]
 [2.94593048]
 [3.82629013]]


In [ ]:
w = tf.Variable(1.0)
b = tf.Variable(0.5)
