In [1]:
from scipy import sparse

In [2]:
import numpy as np
eye = np.eye(4)
print('Numpy array: \n{}'.format(eye))

Numpy array: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
sparse_matrix = sparse.csr_matrix(eye)
print('\n Scipy sparse CSR matrix:\n{}'.format(sparse_matrix))


 Scipy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [4]:
data =np.ones(4)
row_indices= np.arange(4)
col_indices =np.arange(4)
eye_coo= sparse.coo_matrix((data, (row_indices,col_indices)))
print('COO representation:\n{}'.format(eye_coo))

COO representation:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
