In [1]:
import sys
print("Python version: {}".format(sys.version))

Python version: 3.10.3 (main, Apr 20 2022, 19:11:59) [Clang 13.1.6 (clang-1316.0.21.2.3)]


In [2]:
import pandas as  pd
print(f'pandas version: {pd.__version__}')

pandas version: 1.4.3


In [3]:
import matplotlib
print(f'matplotlib version: {matplotlib.__version__}')

matplotlib version: 3.5.1


In [4]:
import numpy as np
print(f'Numpy version: {np.__version__}')

Numpy version: 1.22.3


In [5]:
import scipy as  sp
print(f'Scipy version: {sp.__version__}')

Scipy version: 1.8.0


In [6]:
import IPython
print(f'IPython version: {IPython.__version__}')

IPython version: 8.4.0


In [7]:
import sklearn
print(f'scikit-learn version:{sklearn.__version__}')

scikit-learn version:1.0.2


In [8]:
from sklearn.datasets import load_iris
iris_datasets = load_iris()

In [10]:
print('Keys of iris_dataset:  \n{}'.format(iris_datasets.keys()))

Keys of iris_dataset:  
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [11]:
print(iris_datasets['DESCR'][:193] + '\n...')

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [12]:
print('Target names: {}'.format(iris_datasets['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [14]:
print('Feature name: \n{}'.format(iris_datasets['feature_names']))

Feature name: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [15]:
print('Type of data: {}'.format(type(iris_datasets['data'])))

Type of data: <class 'numpy.ndarray'>


In [16]:
print('Shape of data: {}'.format(iris_datasets['data'].shape))

Shape of data: (150, 4)


In [17]:
print('First five columns of data: \n{}'.format(iris_datasets['data'][:5]))

First five columns of data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [18]:
print('Typeod target: {}'.format(type(iris_datasets['target'])))

Typeod target: <class 'numpy.ndarray'>


In [19]:
print('Shape of target: {}'.format(iris_datasets['target'].shape))

Shape of target: (150,)


In [20]:
print('Target: \n{}'.format(iris_datasets['target']))

Target: 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [21]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(iris_datasets['data'], iris_datasets['target'], random_state=0)